name: Lint and Test Extension

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm install
        working-directory: ./frontend
      - run: npm run lint
        name: Lint VSCode
      - run: npm run lint-frontend
        name: Lint Frontend

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm install
        working-directory: ./frontend
      - run: npm run vscode:bundle

  test:
    strategy:
      matrix:
        os: [windows-latest] # macos-latest #ubuntu-latest,
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3
        if: runner.os == 'Linux'
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Install dependencies
        run: |
          choco install python3
        if: runner.os == 'Windows'

      - run: npm install

      - run: npm install
        working-directory: ./frontend

      - run: npm install
      - run: xvfb-run -a npm test
        if: runner.os == 'Linux'
      - run: npm test
        if: runner.os != 'Linux'
